/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const a_businesspartner_Logic = require('./code/a_businesspartner-logic');

class RiskManagementService extends LCAPApplicationService {
    async init() {

        this.on('READ', 'A_BusinessPartner', async (request, next) => {
            return a_businesspartner_Logic(request, next);
        });

        return super.init();
    }
}


module.exports = {
    RiskManagementService
};